# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.Button_1.setGeometry(QtCore.QRect(109, 10, 70, 21))
        self.Button_1.setObjectName("Button_1")
        self.Button_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(200, 10, 70, 21))
        self.Button_2.setObjectName("Button_2")
        self.Button_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.Button_4.setGeometry(QtCore.QRect(370, 10, 80, 21))
        self.Button_4.setObjectName("Button_4")
        self.Button_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.Button_5.setGeometry(QtCore.QRect(460, 10, 70, 21))
        self.Button_5.setObjectName("Button_5")
        self.Button_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(280, 10, 70, 21))
        self.Button_3.setObjectName("Button_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 580, 40))
        font = QtGui.QFont()
        font.setFamily("Sathu")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 40, 260, 16))
        font = QtGui.QFont()
        font.setFamily(".SF NS Mono")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Change_Text = QtWidgets.QLabel(self.centralwidget)
        self.Change_Text.setGeometry(QtCore.QRect(20, 440, 611, 41))
        self.Change_Text.setObjectName("Change_Text")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 100, 170, 30))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("Option")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 100, 81, 26))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Talyor\'s Photo"))
        self.Button_1.setText(_translate("MainWindow", "증명사진 "))
        self.Button_2.setText(_translate("MainWindow", "내부촬영"))
        self.Button_4.setText(_translate("MainWindow", "바디프로필"))
        self.Button_5.setText(_translate("MainWindow", "웨딩촬영"))
        self.Button_3.setText(_translate("MainWindow", "야외 촬영"))
        self.label.setText(_translate("MainWindow", "메뉴"))
        self.label_2.setText(_translate("MainWindow", "[증명사진 : 20,000] , [내부촬영 : 80,000] ,[야외촬영 : 100,000] ,[바디프로필 : 300,000] ,[웨딩촬영 : 500,000]"))
        self.label_3.setText(_translate("MainWindow", "Menu Table"))
        self.Change_Text.setText(_translate("MainWindow", "옵션 "))
        self.pushButton.setText(_translate("MainWindow", "옵션 선택"))
